name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # GITHUB_RUN_NUMBER always starts from 1, so to maintain compatibility we adjust it here
    - name: Make GITHUB_RUN_NUMBER env var available to Java
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: |
        echo GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER} >> $GITHUB_ENV
        echo JAVA_OPTS="-Dbuild.number=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

    - name: Run tests
      run: sbt test

    - name: Build and package
      run: sbt universal:packageZipTarball rpm:packageBin debian:packageBin

    - name: Publish tarball
      uses: actions/upload-artifact@v3
      with:
        name: Tarball
        path: target/universal/connection_census_beacon-1.0.tgz

    - name: Publish RPM
      uses: actions/upload-artifact@v3
      with:
        name: RPM
        path: target/rpm/RPMS/noarch/connection_census_beacon-1.0-${GITHUB_RUN_NUMBER}.noarch.rpm

    - name: Publish DEB
      uses: actions/upload-artifact@v3
      with:
        name: DEB
        path: target/connection-census-beacon_1.0-${GITHUB_RUN_NUMBER}_all.deb
